### ISSUE TITLE
Data, model

### ISSUE THREAD

**Issue by songuyenerza** [SeaRecluse/4th-Face-Anti-spoofing-Challenge-Team-SeaRecluse-main-CVPR2023#1]
i am student, Can you share with me dataset or model pretrained, thanksss

**Comment by SeaRecluse** [comment]
If you need data, you can apply at the link below.
https://sites.google.com/view/face-anti-spoofing-challenge/dataset-download/uniattackdatacvpr2024 

Regarding the pre-trained model, we have no plans to release the model for the time being.
